book_directory/urls.py
from django.urls import path

from . import views

app_name = "book_directory"
urlpatterns = [
    path('', views.index, name='index'),
    path('addbook/', views.add_book, name='add_book'),
    path('updatebook/<str:pk>/', views.update_book, name='update_book'),
    path('deletebook/<str:pk>/', views.delete_book, name='delete_book'),
]

book_directory/models.py
from datetime import date
from django.db import models

# Create your models here.
class Book(models.Model):
    book_number = models.CharField(max_length=20, unique=True)
    title = models.CharField(max_length=200, blank=True)
    author = models.CharField(max_length=200, blank=True)
    year = models.DateField(default=date.min, blank=True)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class BookStore(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    count = models.IntegerField(default=0)

    def __str__(self):
        return self.book

book_directory/forms.py
from django.forms import ModelForm

from .models import Book

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

book_directory/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models.functions import Lower

from .models import Book
from .forms import BookForm
from .filters import BookFilter

class PaginationContext:
    def __init__(self, items, page=1, items_per_page=10):
        self.items = items
        self.page = page
        self.items_per_page = items_per_page
        self.previous = self.page - 1
        self.is_previous = self.previous >= 1 
        self.next = self.page + 1
        self.is_next = self.items_per_page*self.page < self.items.count() 
        self.pages = range(1, self.items.count() % self.items_per_page)
    
    def get_items(self):
        return self.items[self.items_per_page*(self.page-1) : self.items_per_page*self.page]


def index(request):
    # The books most be ordered by the book number by default
    orderby = request.GET.get('orderby', 'book_number')
    page = int(request.GET.get('p', 1))

    # Process data
    books = Book.objects.all()
    book_count = books.count()
    bookFilter = BookFilter(request.GET, queryset=books)

    books = bookFilter.qs
    books = books.order_by(Lower(orderby))

    # Pagination
    pagination = PaginationContext(books, page)
    books = pagination.get_items()

    ctx = {
        'books': books,
        'book_count': book_count,
        'bookFilter': bookFilter,
        'pagination': pagination,
    }

    return render(request, 'book_directory/index.html', ctx)


def add_book(request):
    form = BookForm()

    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('../')

    ctx = {
        'form': form
    }
    return render(request, 'book_directory/book_form.html', ctx)


def update_book(request, pk):
    book = get_object_or_404(Book, id=pk)
    form = BookForm(instance=book)

    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect('../../')

    ctx = {
        'form': form,
        'book': book,
    }
    return render(request, 'book_directory/book_form.html', ctx)


def delete_book(request, pk):
    book = get_object_or_404(Book, id=pk)

    if request.method == 'POST':
        book.delete()
        return redirect('../../')

    ctx = {
        'book': book,
    }
    return render(request, 'book_directory/delete_book.html', ctx)

book_directory/templates/book_directory/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Book directory</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="book, directory, libro, directorio"/>
    <meta name="description" content="Book directory for local library">
    <meta name="author" content="AngelD-F">

    <link rel="icon" type="image/png" href="{% static 'book_directory/img/favicon.png' %}">
    
    <!--Bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <style>
        body{
            background-color: azure;
        }

        .book-item {
            background-color: ghostwhite;
        }
        .book-item:hover{
            background-color: #e8e8ef;
        }
        .book-item a h6,
        .book-item a h5,
        .book-item a p {
            text-align: left;
        }
        .book-item a h5{
            text-align: justify; 
            text-justify: inter-word;
        }

        .pagination-color li a{
            background-color: floralwhite;
            color: #3a322d;

        }

    </style>
</head>
<body>
    {% include 'book_directory/navbar.html' %}

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    
    {% include 'book_directory/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

book_directory/templates/book_directory/book_form.html
{% extends 'book_directory/base.html' %}
{% block content %}

<div class="card mt-2">
    <div class="card-body">
        <form action method="POST">
            {% csrf_token %}
            {{form}}
            <input class="" type="submit" name="submit"/>
        </form>
    </div>
    {% if book %}
    <div class="card-footer">
        <a href="{% url 'book_directory:delete_book' book.id %}" class="btn btn-outline-danger">Borrar libro</a>
    </div>
    {% endif %}
</div>

{% endblock %}

book_directory/templates/book_directory/delete_book.html
{% extends 'book_directory/base.html' %}
{% block content %}

<div class="card mt-2">
    <div class="card-body">
        <h3 class="card-title">Estas seguro de eliminar este libro de la base de datos?</h3>
        <div class="m-3">
            <p class="card-text">Estas eliminando: <b>[{{book.book_number}}] {{book.title}}</b></p>

            <form class="text-center" action method="POST">
                {% csrf_token %}
                <a class="btn btn-warning mx-2" href="{% url 'book_directory:update_book' book.id %}">Cancelar</a>

                <button class="btn btn-danger mx-2" type="submit" name="Confirm">Borrar</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

book_directory/templates/book_directory/footer.html
{% load static %}
<div class="container">
    <footer class="d-flex justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-muted">© 2022 AngelD-F</p>

        <ul class="nav col-md-4 align-self-center justify-content-center">
            <li class="nav-item">
                <span class="px-2 nav-link text-muted">Programa distribuido bajo la
                    <a href="https://github.com/AngelD-F/book_directory/blob/main/LICENSE" class="">Licencia MIT</a>
                </span>
            </li>
        </ul>

        <a href="https://github.com/AngelD-F/book_directory"
            class="col-md-4 d-flex align-middle justify-content-end mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
            <img src="{% static 'book_directory/img/github.png' %}" width="32" height="32" />
        </a>
    </footer>
</div>

book_directory/templates/book_directory/index.html
{% extends 'book_directory/base.html' %}
{% block content %}
<div class="card mt-2">
    <div class="card-body">
        <form method="get">
            {{bookFilter.form}}
            <button class="btn btn-primary" type="submit">Search</button>
        </form>
    </div>
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md">Total: {{book_count}}</div>
                <form class="col-md" method="get" name="index">
                    <input type="hidden" name="p" value="{{request.GET.p|default:'1'}}"/>
                    <button type="submit" name="orderby" value="book_number" class="btn btn-primary">Ordenar por numero
                        de libro</button>
                        <button type="submit" name="orderby" value="title" class="btn btn-primary">Ordenar por
                            titulo</button>
                </form>
            </div>
        </div>
        <ul class="list-group list-group-flush">
            {% for book in books %}
            <li class="list-group-item book-item">
                <a class="btn w-100" href="{% url 'book_directory:update_book' book.id %}">
                    <h6 class="text-muted">{{book.book_number}}</h6>
                    <h5 class="card-title">{{book.title}}</h5>
                    <p class="card-text">Cantidad: {{book.count}}</p>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% if book_count > 10 %}
    <div class="card-footer">
        <nav aria-label="Page navigation example">
            <form method="get" name="index">
                <ul class="pagination justify-content-center pagination-color">
                    {% if pagination.is_previous %}
                    <li class="page-item">
                        <button type="submit" name="p" value="{{pagination.previous}}" class="page-link"
                            aria-label="Previous" >
                        <span aria-hidden="true">&laquo;</span></button>
                    </li>
                    {% endif %}
                    {% for page in pagination.pages %}
                    <li class="page-item"><button type="submit" name="p" value="{{page}}" class="page-link" >{{page}}</button>
                    </li>
                    {% endfor %}
                    {% if pagination.is_next %}
                    <li class="page-item">
                        <button type="submit" name="p" value="{{pagination.next}}" class="page-link" aria-label="Next" >
                        <span aria-hidden="true">&raquo;</span></button>
                    </li>
                    {% endif %}
                    <input type="hidden" name="orderby" value="{{request.GET.orderby|default:'book_number'}}"/>
                </ul>
            </form>
        </nav>
    </div>
    {% endif %}
</div>
{% endblock %}

book_directory/templates/book_directory/navbar.html
{% load static %}

<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="{% url 'book_directory:index' %}" class="d-flex me-lg-auto align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img class="bi me-2" width="200" src="{% static 'book_directory/img/nav_header.png' %}"/>
            </a>
            <div class="text-end py-1">
                <a href="{% url 'book_directory:add_book' %}">
                    <button type="button" class="btn btn-warning">Agregar libro</button>
                </a>
            </div>
        </div>
    </div>
</header>